package com.tron.common.util;

import android.content.Context;
import android.content.SharedPreferences;
import android.preference.PreferenceManager;
import android.util.Base64;

/**
 * Created by Angga
 * to manage Shared Preference
 * the static sharedPreferences should be generated by BaseActivity
 * to passing its context to init method
 */
public class Pref {

    public static final String INTENT_AMOUNT = "intent_amount";
    public static final String FROM_ANOTHER_APP = "from_another_app";
    public static final String FROM_CLOUD_APP = "from_cloud_app";
    public static final String PAYMENT_METHOD = "payment_method";
    public static final String POS_CLOUD_POINTER = "pos_cloud_printer";
    public static final String POS_REQUEST_TYPE = "request_type";
    public static final String POS_EDC_TYPE = "pos_edc_type";
    public static final String CREDIT_DEBIT = "credit_debit";
    public static final String GOPAY = "gopay";
    public static final String OVO = "ovo";
    public static final String DANA = "dana";
    public static final String LINK_AJA = "link_aja";
    public static final String ENV = "env";
    public static final String APP_CONFIG_GENERAL_TIMESTAMP = "app_config_general_timestamp";
    public static final String APP_CONFIG_QR_TIMESTAMP = "app_config_qr_timestamp";
    public static final String APP_CONFIG_GENERAL = "app_config_general";
    public static final String APP_CONFIG_QR = "app_config_qr";
    public static final String IS_NEED_EXTERNAL_PRINTER = "is_need_external_printer";
    public static final String POS_INTENT_POINTER = "pos_intent_pointer";
    public static final String FEATURE_FLOW = "feature_flow";
    public static final String LAST_TRX = "last_trx";
    public static final String PREPAID_BIN_AID = "prepaid_bin_aid";
    public static final String TAP_CASH_TRX_LIST = "tap_cash_trx_list";
    public static final String PREPAID_INVOICE_CONFIG = "prepaid_invoice_config";
    public static final String PREPAID_INVOICE_LOCAL = "prepaid_invoice_local";
    public static final String PREPAID_BATCH_CONFIG = "prepaid_batch_config";
    public static final String LAST_TIME_LOGON_PCPS = "last_time_logon_pcps";
    public static final String LAST_TIME_CHECK_SAM = "last_time_check_sam";
    public static final String PREPAID_BANK_INFO_LIST = "prepaid_bank_info_list";
    private static SharedPreferences sharedPreferences;

    public static void init(Context context) {
        sharedPreferences = PreferenceManager.getDefaultSharedPreferences(context);
    }

    public static String getString(String key) {
        return new String(Base64.decode(sharedPreferences.getString(key, ""), 0));
    }

    public static void setString(String key, String value) {
        SharedPreferences.Editor editor = sharedPreferences.edit();
        editor.putString(key, Base64.encodeToString(value.getBytes(), 0));
        editor.apply();
    }

    public static int getInt(String key) {
        return sharedPreferences.getInt(key, 0);
    }

    public static void setInt(String key, int value) {
        SharedPreferences.Editor editor = sharedPreferences.edit();
        editor.putInt(key, value);
        editor.apply();
    }

    public static boolean getBool(String key) {
        return sharedPreferences.getBoolean(key, false);
    }

    public static void setBool(String key, boolean value) {
        SharedPreferences.Editor editor = sharedPreferences.edit();
        editor.putBoolean(key, value);
        editor.apply();
    }

    public static long getLong(String key) {
        return sharedPreferences.getLong(key, 0);
    }

    public static void setLong(String key, long value) {
        SharedPreferences.Editor editor = sharedPreferences.edit();
        editor.putLong(key, value);
        editor.apply();
    }
}
